language: python
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install --upgrade pip setuptools
  - pip install $DJANGO
script:
  - python setup.py test